# Generated by Django 4.0.4 on 2022-05-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aadhar',
            options={'ordering': ['aadhar_number'], 'verbose_name_plural': 'Aadhar'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['bank_name']},
        ),
        migrations.AlterModelOptions(
            name='pastjobexperience',
            options={'ordering': ['year_experience'], 'verbose_name_plural': 'Past Job Experience'},
        ),
        migrations.AlterModelOptions(
            name='personaldetails',
            options={'verbose_name_plural': 'Personal Details'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['year_of_passing']},
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to='tables.aadhar'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_user', to='tables.aadhar'),
        ),
        migrations.AlterField(
            model_name='pastjobexperience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_job_experience_user', to='tables.aadhar'),
        ),
        migrations.AlterField(
            model_name='pastjobexperience',
            name='year_experience',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_details_user', to='tables.aadhar'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_user', to='tables.aadhar'),
        ),
    ]
